package net.ludocrypt.corners.init;

import net.ludocrypt.corners.TheCorners;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.bus.api.IEventBus;
import java.util.function.Supplier;
import net.minecraft.core.Holder;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.sounds.SoundEvent;

public class CornerSoundEvents {

    public static final DeferredRegister<SoundEvent> SOUND_EVENTS = DeferredRegister.create(BuiltInRegistries.SOUND_EVENT, "corners");

    public static void register(IEventBus bus) {
        SOUND_EVENTS.register(bus);
    }

	// Misc
	public static final Supplier<SoundEvent> PAINTING_PORTAL_TRAVEL = SOUND_EVENTS.register("misc.portal.painting.travel", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("misc.portal.painting.travel")));
	// Music
	public static final Supplier<SoundEvent> MUSIC_YEARNING_CANAL = SOUND_EVENTS.register("music.yearning_canal", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("music.yearning_canal")));
	public static final Supplier<SoundEvent> MUSIC_COMMUNAL_CORRIDORS = SOUND_EVENTS.register("music.communal_corridors", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("music.communal_corridors")));
	public static final Supplier<SoundEvent> MUSIC_COMMUNAL_CORRIDORS_CHRISTMAS = SOUND_EVENTS.register(
		"music.communal_corridors.christmas", () -> SoundEvent.createVariableRangeEvent(TheCorners.id(
		"music.communal_corridors.christmas")));
	public static final Supplier<SoundEvent> MUSIC_HOARY_CROSSROADS = SOUND_EVENTS.register("music.hoary_crossroads", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("music.hoary_crossroads")));
	// Radio
	public static final Supplier<SoundEvent> RADIO_DEFAULT_STATIC = SOUND_EVENTS.register("radio.default.static", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("radio.default.static")));
	public static final Supplier<SoundEvent> RADIO_YEARNING_CANAL = SOUND_EVENTS.register("radio.yearning_canal", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("radio.yearning_canal")));
	public static final Supplier<SoundEvent> RADIO_COMMUNAL_CORRIDORS = SOUND_EVENTS.register("radio.communal_corridors", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("radio.communal_corridors")));
	public static final Supplier<SoundEvent> RADIO_HOARY_CROSSROADS = SOUND_EVENTS.register("radio.hoary_crossroads", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("radio.hoary_crossroads")));
	public static final Supplier<SoundEvent> RADIO_YEARNING_CANAL_STATIC = SOUND_EVENTS.register("radio.yearning_canal.static", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("radio.yearning_canal.static")));
	public static final Supplier<SoundEvent> RADIO_COMMUNAL_CORRIDORS_STATIC = SOUND_EVENTS.register(
		"radio.communal_corridors.static", () -> SoundEvent.createVariableRangeEvent(TheCorners.id(
		"radio.communal_corridors.static")));
	public static final Supplier<SoundEvent> RADIO_HOARY_CROSSROADS_STATIC = SOUND_EVENTS.register("radio.hoary_crossroads.static", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("radio.hoary_crossroads.static")));
	public static final Supplier<SoundEvent> RADIO_YEARNING_CANAL_MUSIC = SOUND_EVENTS.register("radio.yearning_canal.music", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("radio.yearning_canal.music")));
	public static final Supplier<SoundEvent> RADIO_COMMUNAL_CORRIDORS_MUSIC = SOUND_EVENTS.register("radio.communal_corridors.music", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("radio.communal_corridors.music")));
	public static final Supplier<SoundEvent> RADIO_HOARY_CROSSROADS_MUSIC = SOUND_EVENTS.register("radio.hoary_crossroads.music", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("radio.hoary_crossroads.music")));
	// Ambient
	public static final Supplier<SoundEvent> BIOME_LOOP_COMMUNAL_CORRIDORS = SOUND_EVENTS.register("biome.communal_corridors.loop", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("biome.communal_corridors.loop")));
	public static final Supplier<SoundEvent> BIOME_LOOP_HOARY_CROSSROADS = SOUND_EVENTS.register("biome.hoary_crossroads.loop", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("biome.hoary_crossroads.loop")));
	public static final Supplier<SoundEvent> BIOME_LOOP_THE_ABYSS = SOUND_EVENTS.register("biome.the_abyss.loop", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("biome.the_abyss.loop")));
	public static final Supplier<SoundEvent> ENGULFING_DARKNESS_HEARTBEAT = SOUND_EVENTS.register("darkness.heartbeat", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("darkness.heartbeat")));
	public static final Supplier<SoundEvent> ENGULFING_DARKNESS_WHISPER = SOUND_EVENTS.register("darkness.whisper", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("darkness.whisper")));
	public static final Supplier<SoundEvent> EYES_IN_DARKNESS_VANISH = SOUND_EVENTS.register("darkness.eyes_vanish", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("darkness.eyes_vanish")));
	public static final Supplier<SoundEvent> DFJN = SOUND_EVENTS.register("dfjn", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("dfjn")));
	public static final Supplier<SoundEvent> DOOR1 = SOUND_EVENTS.register("door1", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("door1")));
	public static final Supplier<SoundEvent> DOOR2 = SOUND_EVENTS.register("door2", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("door2")));
	public static final Supplier<SoundEvent> SERPUMPKINHEADM = SOUND_EVENTS.register("serpumpkinheadm", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("serpumpkinheadm")));
	public static final Supplier<SoundEvent> RESTLESS_SPIRIT_IDLE = SOUND_EVENTS.register("restless_spirit_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("restless_spirit_idle")));
	public static final Supplier<SoundEvent> RESTLESS_SPIRIT_HURT = SOUND_EVENTS.register("restless_spirit_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("restless_spirit_hurt")));
	public static final Supplier<SoundEvent> RESTLESS_SPIRIT_DEATH = SOUND_EVENTS.register("restless_spirit_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("restless_spirit_death")));
	public static final Supplier<SoundEvent> SKELETON_TRASHER_STEP = SOUND_EVENTS.register("skeleton_trasher_step", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("skeleton_trasher_step")));
	public static final Supplier<SoundEvent> SKELETON_TRASHER_ATTACK = SOUND_EVENTS.register("skeleton_trasher_attack", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("skeleton_trasher_attack")));
	public static final Supplier<SoundEvent> SKELETON_TRASHER_BLOCK1 = SOUND_EVENTS.register("skeleton_trasher_block1", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("skeleton_trasher_block1")));
	public static final Supplier<SoundEvent> SKELETON_TRASHER_BLOCK2 = SOUND_EVENTS.register("skeleton_trasher_block2", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("skeleton_trasher_block2")));
	public static final Supplier<SoundEvent> SKELETON_TRASHER_BLOCK3 = SOUND_EVENTS.register("skeleton_trasher_block3", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("skeleton_trasher_block3")));
	public static final Supplier<SoundEvent> NIGHTMARE_STALKER_ROAR = SOUND_EVENTS.register("nightmare_stalker_roar", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("nightmare_stalker_roar")));
	public static final Supplier<SoundEvent> SPIRIT_IDLE = SOUND_EVENTS.register("spirit_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("spirit_idle")));
	public static final Supplier<SoundEvent> STALKER_DEATH = SOUND_EVENTS.register("stalker_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stalker_death")));
	public static final Supplier<SoundEvent> VORTEX_HURT1 = SOUND_EVENTS.register("vortex_hurt1", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("vortex_hurt1")));
	public static final Supplier<SoundEvent> VORTEX_HURT2 = SOUND_EVENTS.register("vortex_hurt2", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("vortex_hurt2")));
	public static final Supplier<SoundEvent> VORTEX_IDLE1 = SOUND_EVENTS.register("vortex_idle1", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("vortex_idle1")));
	public static final Supplier<SoundEvent> FALLEN_ATTACK = SOUND_EVENTS.register("fallen_attack", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("fallen_attack")));
	public static final Supplier<SoundEvent> FALLEN_CURSE_MARK = SOUND_EVENTS.register("fallen_curse_mark", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("fallen_curse_mark")));
	public static final Supplier<SoundEvent> FALLEN_DEATH = SOUND_EVENTS.register("fallen_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("fallen_death")));
	public static final Supplier<SoundEvent> FALLEN_HURT = SOUND_EVENTS.register("fallen_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("fallen_hurt")));
	public static final Supplier<SoundEvent> FALLEN_IDLE = SOUND_EVENTS.register("fallen_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("fallen_idle")));
	public static final Supplier<SoundEvent> FALLEN_STEP = SOUND_EVENTS.register("fallen_step", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("fallen_step")));
	public static final Supplier<SoundEvent> PERSECUTOR_DEATH = SOUND_EVENTS.register("persecutor_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("persecutor_death")));
	public static final Supplier<SoundEvent> PERSECUTOR_HURT = SOUND_EVENTS.register("persecutor_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("persecutor_hurt")));
	public static final Supplier<SoundEvent> PERSECUTOR_IDLE = SOUND_EVENTS.register("persecutor_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("persecutor_idle")));
	public static final Supplier<SoundEvent> PERSECUTOR_SCREAM = SOUND_EVENTS.register("persecutor_scream", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("persecutor_scream")));
	public static final Supplier<SoundEvent> STALKER_DEATH2 = SOUND_EVENTS.register("stalker_death2", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stalker_death2")));
	public static final Supplier<SoundEvent> VORTEX_DEATH1 = SOUND_EVENTS.register("vortex_death1", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("vortex_death1")));
	public static final Supplier<SoundEvent> VORTEX_IDLE2 = SOUND_EVENTS.register("vortex_idle2", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("vortex_idle2")));
	public static final Supplier<SoundEvent> VORTEX_HURT11 = SOUND_EVENTS.register("vortex_hurt11", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("vortex_hurt11")));
	public static final Supplier<SoundEvent> VORTEX_HURT21 = SOUND_EVENTS.register("vortex_hurt21", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("vortex_hurt21")));
	public static final Supplier<SoundEvent> HAH = SOUND_EVENTS.register("hah", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hah")));
	public static final Supplier<SoundEvent> HAHA = SOUND_EVENTS.register("haha", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("haha")));
	public static final Supplier<SoundEvent> DOORBLOKC = SOUND_EVENTS.register("doorblokc", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("doorblokc")));
	public static final Supplier<SoundEvent> DOORBLOKC2 = SOUND_EVENTS.register("doorblokc2", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("doorblokc2")));
	public static final Supplier<SoundEvent> HALLOWEEN = SOUND_EVENTS.register("halloween", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("halloween")));
	public static final Supplier<SoundEvent> DOORSDISC = SOUND_EVENTS.register("doorsdisc", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("doorsdisc")));
	public static final Supplier<SoundEvent> STALKER_ROAR = SOUND_EVENTS.register("stalker_roar", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stalker_roar")));
	public static final Supplier<SoundEvent> STALKER_DEAD = SOUND_EVENTS.register("stalker_dead", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stalker_dead")));
	public static final Supplier<SoundEvent> STALKER_STEP = SOUND_EVENTS.register("stalker_step", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stalker_step")));
	public static final Supplier<SoundEvent> STALKER_HIT = SOUND_EVENTS.register("stalker_hit", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stalker_hit")));
	public static final Supplier<SoundEvent> STALKER_HURT = SOUND_EVENTS.register("stalker_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stalker_hurt")));
	public static final Supplier<SoundEvent> PUMPKIN_SPIRIT_HURT = SOUND_EVENTS.register("pumpkin_spirit_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pumpkin_spirit_hurt")));
	public static final Supplier<SoundEvent> PUMPKIN_SPIRIT_DEATH = SOUND_EVENTS.register("pumpkin_spirit_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pumpkin_spirit_death")));
	public static final Supplier<SoundEvent> STALKER_ROAR_DISTANT = SOUND_EVENTS.register("stalker_roar_distant", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stalker_roar_distant")));
	public static final Supplier<SoundEvent> HOUND_DEATH = SOUND_EVENTS.register("hound_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hound_death")));
	public static final Supplier<SoundEvent> HOUND_HIT = SOUND_EVENTS.register("hound_hit", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hound_hit")));
	public static final Supplier<SoundEvent> HOUND_AMBIENT = SOUND_EVENTS.register("hound_ambient", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hound_ambient")));
	public static final Supplier<SoundEvent> HOUND_ATTACK = SOUND_EVENTS.register("hound_attack", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hound_attack")));
	public static final Supplier<SoundEvent> SEARED_SPIRIT_DEATH = SOUND_EVENTS.register("seared_spirit_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("seared_spirit_death")));
	public static final Supplier<SoundEvent> HOUNDTRAP = SOUND_EVENTS.register("houndtrap", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("houndtrap")));
	public static final Supplier<SoundEvent> DARK_WARLBLADE_ATAK = SOUND_EVENTS.register("dark_warlblade_atak", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("dark_warlblade_atak")));
	public static final Supplier<SoundEvent> STOMACH_OPEN = SOUND_EVENTS.register("stomach_open", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stomach_open")));
	public static final Supplier<SoundEvent> CLOWN_STEP = SOUND_EVENTS.register("clown_step", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("clown_step")));
	public static final Supplier<SoundEvent> CLOWN_HURT = SOUND_EVENTS.register("clown_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("clown_hurt")));
	public static final Supplier<SoundEvent> CLOWN_DEATH = SOUND_EVENTS.register("clown_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("clown_death")));
	public static final Supplier<SoundEvent> ZOMBIE_CLOWN_ATTACK = SOUND_EVENTS.register("zombie_clown_attack", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("zombie_clown_attack")));
	public static final Supplier<SoundEvent> CORPSE_FLY_AMBIENT = SOUND_EVENTS.register("corpse_fly_ambient", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("corpse_fly_ambient")));
	public static final Supplier<SoundEvent> CORPSE_FLY_DEATH = SOUND_EVENTS.register("corpse_fly_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("corpse_fly_death")));
	public static final Supplier<SoundEvent> CORPSE_FLY_HURT = SOUND_EVENTS.register("corpse_fly_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("corpse_fly_hurt")));
	public static final Supplier<SoundEvent> GADFLY_IDLE = SOUND_EVENTS.register("gadfly_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("gadfly_idle")));
	public static final Supplier<SoundEvent> GADFLY_HURT = SOUND_EVENTS.register("gadfly_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("gadfly_hurt")));
	public static final Supplier<SoundEvent> GADFLY_DEATH = SOUND_EVENTS.register("gadfly_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("gadfly_death")));
	public static final Supplier<SoundEvent> CORPSE_FLY_AMBIENT2 = SOUND_EVENTS.register("corpse_fly_ambient2", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("corpse_fly_ambient2")));
	public static final Supplier<SoundEvent> CORPSE_FLY_HURT2 = SOUND_EVENTS.register("corpse_fly_hurt2", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("corpse_fly_hurt2")));
	public static final Supplier<SoundEvent> CORPSE_FLY_DEATH2 = SOUND_EVENTS.register("corpse_fly_death2", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("corpse_fly_death2")));
	public static final Supplier<SoundEvent> FISH_SLAP = SOUND_EVENTS.register("fish_slap", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("fish_slap")));
	public static final Supplier<SoundEvent> SWARMER_IDLE = SOUND_EVENTS.register("swarmer_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("swarmer_idle")));
	public static final Supplier<SoundEvent> SWARMER_HURT = SOUND_EVENTS.register("swarmer_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("swarmer_hurt")));
	public static final Supplier<SoundEvent> SWARMER_DEATH = SOUND_EVENTS.register("swarmer_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("swarmer_death")));
	public static final Supplier<SoundEvent> CRAB_DEATH = SOUND_EVENTS.register("crab_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("crab_death")));
	public static final Supplier<SoundEvent> CRAB_IDLE = SOUND_EVENTS.register("crab_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("crab_idle")));
	public static final Supplier<SoundEvent> CRAB_STEP = SOUND_EVENTS.register("crab_step", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("crab_step")));
	public static final Supplier<SoundEvent> CRAB_HURT = SOUND_EVENTS.register("crab_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("crab_hurt")));
	public static final Supplier<SoundEvent> GLUTTON_FISH_AMBIENT = SOUND_EVENTS.register("glutton_fish_ambient", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("glutton_fish_ambient")));
	public static final Supplier<SoundEvent> GLUTTON_FISH_ATTACK = SOUND_EVENTS.register("glutton_fish_attack", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("glutton_fish_attack")));
	public static final Supplier<SoundEvent> GLUTTON_FISH_HURT = SOUND_EVENTS.register("glutton_fish_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("glutton_fish_hurt")));
	public static final Supplier<SoundEvent> GLUTTON_FISH_DEATH = SOUND_EVENTS.register("glutton_fish_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("glutton_fish_death")));
	public static final Supplier<SoundEvent> FLY_MOVE = SOUND_EVENTS.register("fly_move", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("fly_move")));
	public static final Supplier<SoundEvent> BRUTE_ZOMBIE_ATTACK = SOUND_EVENTS.register("brute_zombie_attack", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("brute_zombie_attack")));
	public static final Supplier<SoundEvent> BRUTE_ZOMBIE_STEP = SOUND_EVENTS.register("brute_zombie_step", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("brute_zombie_step")));
	public static final Supplier<SoundEvent> ZOMBIE_BRUTE_DEATH = SOUND_EVENTS.register("zombie_brute_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("zombie_brute_death")));
	public static final Supplier<SoundEvent> ZOMBIE_BRUTE_HURT = SOUND_EVENTS.register("zombie_brute_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("zombie_brute_hurt")));
	public static final Supplier<SoundEvent> ZOMBIE_BRUTE_IDLE = SOUND_EVENTS.register("zombie_brute_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("zombie_brute_idle")));
	public static final Supplier<SoundEvent> PUMPKINHEAD_RELOAD = SOUND_EVENTS.register("pumpkinhead_reload", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pumpkinhead_reload")));
	public static final Supplier<SoundEvent> PUMPKINHEAD_GUN_FIRE = SOUND_EVENTS.register("pumpkinhead_gun_fire", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pumpkinhead_gun_fire")));
	public static final Supplier<SoundEvent> PUMPKINHEAD_BOMB_CURSE = SOUND_EVENTS.register("pumpkinhead_bomb_curse", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pumpkinhead_bomb_curse")));
	public static final Supplier<SoundEvent> CHARM_OF_STEALTH_USE = SOUND_EVENTS.register("charm_of_stealth_use", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("charm_of_stealth_use")));
	public static final Supplier<SoundEvent> CHARM_OF_ENDURANCE_USE = SOUND_EVENTS.register("charm_of_endurance_use", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("charm_of_endurance_use")));
	public static final Supplier<SoundEvent> CHARM_OF_STRENGHT_USE = SOUND_EVENTS.register("charm_of_strenght_use", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("charm_of_strenght_use")));
	public static final Supplier<SoundEvent> CHARM_OF_RAGE_USE = SOUND_EVENTS.register("charm_of_rage_use", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("charm_of_rage_use")));
	public static final Supplier<SoundEvent> CHARM_OF_PROTECTION_USE = SOUND_EVENTS.register("charm_of_protection_use", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("charm_of_protection_use")));
	public static final Supplier<SoundEvent> MISSIONARY_DEATH = SOUND_EVENTS.register("missionary_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("missionary_death")));
	public static final Supplier<SoundEvent> MISSIONARY_HURT = SOUND_EVENTS.register("missionary_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("missionary_hurt")));
	public static final Supplier<SoundEvent> MISSIONARY_IDLE = SOUND_EVENTS.register("missionary_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("missionary_idle")));
	public static final Supplier<SoundEvent> MISSIONARY_SPAWN_MOBS = SOUND_EVENTS.register("missionary_spawn_mobs", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("missionary_spawn_mobs")));
	public static final Supplier<SoundEvent> MISSIONARY_STEP = SOUND_EVENTS.register("missionary_step", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("missionary_step")));
	public static final Supplier<SoundEvent> MISSIONARY_TELEPORT = SOUND_EVENTS.register("missionary_teleport", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("missionary_teleport")));
	public static final Supplier<SoundEvent> MISSIONARY_SHOOT = SOUND_EVENTS.register("missionary_shoot", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("missionary_shoot")));
	public static final Supplier<SoundEvent> OBSESSION = SOUND_EVENTS.register("obsession", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("obsession")));
	public static final Supplier<SoundEvent> CHAOS_SPIRIT_HAUNT = SOUND_EVENTS.register("chaos_spirit_haunt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("chaos_spirit_haunt")));
	public static final Supplier<SoundEvent> MISSIONARY_ALERT = SOUND_EVENTS.register("missionary_alert", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("missionary_alert")));
	public static final Supplier<SoundEvent> NSSTEP = SOUND_EVENTS.register("nsstep", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("nsstep")));
	public static final Supplier<SoundEvent> STEP5 = SOUND_EVENTS.register("step5", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("step5")));
	public static final Supplier<SoundEvent> STEP_ST = SOUND_EVENTS.register("step_st", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("step_st")));
	public static final Supplier<SoundEvent> LIFESTEALER_HURT = SOUND_EVENTS.register("lifestealer_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lifestealer_hurt")));
	public static final Supplier<SoundEvent> LIFESTEALER_IDLE = SOUND_EVENTS.register("lifestealer_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lifestealer_idle")));
	public static final Supplier<SoundEvent> LIFESTEALER_DEATH = SOUND_EVENTS.register("lifestealer_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lifestealer_death")));
	public static final Supplier<SoundEvent> LIFESTEALER_SCREAM = SOUND_EVENTS.register("lifestealer_scream", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lifestealer_scream")));
	public static final Supplier<SoundEvent> LIFESTEALER_SCREAM_AP = SOUND_EVENTS.register("lifestealer_scream_ap", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lifestealer_scream_ap")));
	public static final Supplier<SoundEvent> MAGIC_STAFF_SHOOT = SOUND_EVENTS.register("magic_staff_shoot", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("magic_staff_shoot")));
	public static final Supplier<SoundEvent> PUMPKIN_STAFF_SHOOT = SOUND_EVENTS.register("pumpkin_staff_shoot", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pumpkin_staff_shoot")));
	public static final Supplier<SoundEvent> PUMPKIN_HIT = SOUND_EVENTS.register("pumpkin_hit", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pumpkin_hit")));
	public static final Supplier<SoundEvent> SPIDER_SPLASH = SOUND_EVENTS.register("spider_splash", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("spider_splash")));
	public static final Supplier<SoundEvent> MOTHER_SPIDER_STEP = SOUND_EVENTS.register("mother_spider_step", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("mother_spider_step")));
	public static final Supplier<SoundEvent> MOTHER_SPIDER_IDLE = SOUND_EVENTS.register("mother_spider_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("mother_spider_idle")));
	public static final Supplier<SoundEvent> MISSIONARY_STUN = SOUND_EVENTS.register("missionary_stun", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("missionary_stun")));
	public static final Supplier<SoundEvent> MOTHER_SPIDER_HURT = SOUND_EVENTS.register("mother_spider_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("mother_spider_hurt")));
	public static final Supplier<SoundEvent> SPIDER_MOTHER_DEATH = SOUND_EVENTS.register("spider_mother_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("spider_mother_death")));
	public static final Supplier<SoundEvent> HAHA_LORD = SOUND_EVENTS.register("haha_lord", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("haha_lord")));
	public static final Supplier<SoundEvent> BONK = SOUND_EVENTS.register("bonk", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bonk")));
	public static final Supplier<SoundEvent> BONK_HIT = SOUND_EVENTS.register("bonk_hit", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bonk_hit")));
	public static final Supplier<SoundEvent> KRAMPUS_DEATH = SOUND_EVENTS.register("krampus_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_death")));
	public static final Supplier<SoundEvent> KRAMPUS_ROAR = SOUND_EVENTS.register("krampus_roar", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_roar")));
	public static final Supplier<SoundEvent> KRAMPUS_IDLE = SOUND_EVENTS.register("krampus_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_idle")));
	public static final Supplier<SoundEvent> KRAMPUS_BLOW = SOUND_EVENTS.register("krampus_blow", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_blow")));
	public static final Supplier<SoundEvent> KRAMPUS_HORN_USE = SOUND_EVENTS.register("krampus_horn_use", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_horn_use")));
	public static final Supplier<SoundEvent> KRAMPUS_ALERT_FAR = SOUND_EVENTS.register("krampus_alert_far", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_alert_far")));
	public static final Supplier<SoundEvent> KRAMPUS_ALERT = SOUND_EVENTS.register("krampus_alert", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_alert")));
	public static final Supplier<SoundEvent> KRAMPUS_ALERT_CLOSE = SOUND_EVENTS.register("krampus_alert_close", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_alert_close")));
	public static final Supplier<SoundEvent> KRAMPUS_HURT = SOUND_EVENTS.register("krampus_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_hurt")));
	public static final Supplier<SoundEvent> KRAMPUS_STEP = SOUND_EVENTS.register("krampus_step", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("krampus_step")));
	public static final Supplier<SoundEvent> MINION_BLOW = SOUND_EVENTS.register("minion_blow", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("minion_blow")));
	public static final Supplier<SoundEvent> MINION_DEATH = SOUND_EVENTS.register("minion_death", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("minion_death")));
	public static final Supplier<SoundEvent> MINION_HURT = SOUND_EVENTS.register("minion_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("minion_hurt")));
	public static final Supplier<SoundEvent> MINION_IDLE = SOUND_EVENTS.register("minion_idle", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("minion_idle")));
	public static final Supplier<SoundEvent> BOMBER_AMBIENT = SOUND_EVENTS.register("bomber_ambient", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bomber_ambient")));
	public static final Supplier<SoundEvent> BOMBER_READY = SOUND_EVENTS.register("bomber_ready", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bomber_ready")));
	public static final Supplier<SoundEvent> SPECHURT = SOUND_EVENTS.register("spechurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("spechurt")));
	public static final Supplier<SoundEvent> SPECDED = SOUND_EVENTS.register("specded", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("specded")));
	public static final Supplier<SoundEvent> SPECAMB = SOUND_EVENTS.register("specamb", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("specamb")));
	public static final Supplier<SoundEvent> BOMBERHURTS = SOUND_EVENTS.register("bomberhurts", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bomberhurts")));
	public static final Supplier<SoundEvent> BOMBERAMBT = SOUND_EVENTS.register("bomberambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bomberambt")));
	public static final Supplier<SoundEvent> BOMBERDED = SOUND_EVENTS.register("bomberded", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bomberded")));
	public static final Supplier<SoundEvent> SPITTERAM = SOUND_EVENTS.register("spitteram", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("spitteram")));
	public static final Supplier<SoundEvent> SPITTERHURT = SOUND_EVENTS.register("spitterhurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("spitterhurt")));
	public static final Supplier<SoundEvent> ACIDDED = SOUND_EVENTS.register("acidded", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("acidded")));
	public static final Supplier<SoundEvent> HORRORSHURT = SOUND_EVENTS.register("horrorshurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("horrorshurt")));
	public static final Supplier<SoundEvent> HORRORSAMBT = SOUND_EVENTS.register("horrorsambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("horrorsambt")));
	public static final Supplier<SoundEvent> HORRORSDED = SOUND_EVENTS.register("horrorsded", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("horrorsded")));
	public static final Supplier<SoundEvent> WHEEZERDEAD = SOUND_EVENTS.register("wheezerdead", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("wheezerdead")));
	public static final Supplier<SoundEvent> WHEEZERAMBT = SOUND_EVENTS.register("wheezerambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("wheezerambt")));
	public static final Supplier<SoundEvent> WHEEZEHURT = SOUND_EVENTS.register("wheezehurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("wheezehurt")));
	public static final Supplier<SoundEvent> WHEEBOMB = SOUND_EVENTS.register("wheebomb", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("wheebomb")));
	public static final Supplier<SoundEvent> MOONSTEP = SOUND_EVENTS.register("moonstep", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("moonstep")));
	public static final Supplier<SoundEvent> SUCKAMBT = SOUND_EVENTS.register("suckambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("suckambt")));
	public static final Supplier<SoundEvent> SUCKERDIES = SOUND_EVENTS.register("suckerdies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("suckerdies")));
	public static final Supplier<SoundEvent> SUCKERHURTS = SOUND_EVENTS.register("suckerhurts", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("suckerhurts")));
	public static final Supplier<SoundEvent> SPRAY = SOUND_EVENTS.register("spray", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("spray")));
	public static final Supplier<SoundEvent> POP = SOUND_EVENTS.register("pop", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pop")));
	public static final Supplier<SoundEvent> HUNTERAMBT = SOUND_EVENTS.register("hunterambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hunterambt")));
	public static final Supplier<SoundEvent> HUNTERHURTS = SOUND_EVENTS.register("hunterhurts", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hunterhurts")));
	public static final Supplier<SoundEvent> HUNTERFOOTS = SOUND_EVENTS.register("hunterfoots", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hunterfoots")));
	public static final Supplier<SoundEvent> CLANK = SOUND_EVENTS.register("clank", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("clank")));
	public static final Supplier<SoundEvent> HUNTER_FLY = SOUND_EVENTS.register("hunter_fly", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hunter_fly")));
	public static final Supplier<SoundEvent> WOLFORBRUIN_ATTACK = SOUND_EVENTS.register("wolforbruin_attack", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("wolforbruin_attack")));
	public static final Supplier<SoundEvent> WOLFANRGY = SOUND_EVENTS.register("wolfanrgy", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("wolfanrgy")));
	public static final Supplier<SoundEvent> ODURESKING = SOUND_EVENTS.register("oduresking", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("oduresking")));
	public static final Supplier<SoundEvent> SWARMERABMT = SOUND_EVENTS.register("swarmerabmt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("swarmerabmt")));
	public static final Supplier<SoundEvent> SWARMERHURT = SOUND_EVENTS.register("swarmerhurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("swarmerhurt")));
	public static final Supplier<SoundEvent> SWARMERDIES = SOUND_EVENTS.register("swarmerdies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("swarmerdies")));
	public static final Supplier<SoundEvent> SWARMERSTEPS = SOUND_EVENTS.register("swarmersteps", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("swarmersteps")));
	public static final Supplier<SoundEvent> BIDY_AMBT = SOUND_EVENTS.register("bidy_ambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bidy_ambt")));
	public static final Supplier<SoundEvent> BIDYBOOM = SOUND_EVENTS.register("bidyboom", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bidyboom")));
	public static final Supplier<SoundEvent> PRENANTPUKES = SOUND_EVENTS.register("prenantpukes", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("prenantpukes")));
	public static final Supplier<SoundEvent> IMPACT = SOUND_EVENTS.register("impact", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("impact")));
	public static final Supplier<SoundEvent> THEPREGNANT_AMBT = SOUND_EVENTS.register("thepregnant_ambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("thepregnant_ambt")));
	public static final Supplier<SoundEvent> PREGNANTHURT = SOUND_EVENTS.register("pregnanthurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pregnanthurt")));
	public static final Supplier<SoundEvent> PREGNANTDEATH = SOUND_EVENTS.register("pregnantdeath", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("pregnantdeath")));
	public static final Supplier<SoundEvent> WINDBLAST = SOUND_EVENTS.register("windblast", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("windblast")));
	public static final Supplier<SoundEvent> PARRY = SOUND_EVENTS.register("parry", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("parry")));
	public static final Supplier<SoundEvent> THERODCHARG = SOUND_EVENTS.register("therodcharg", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("therodcharg")));
	public static final Supplier<SoundEvent> RODSTEP = SOUND_EVENTS.register("rodstep", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("rodstep")));
	public static final Supplier<SoundEvent> THERODHURTS = SOUND_EVENTS.register("therodhurts", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("therodhurts")));
	public static final Supplier<SoundEvent> RODAMBIENCE = SOUND_EVENTS.register("rodambience", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("rodambience")));
	public static final Supplier<SoundEvent> RODDIES = SOUND_EVENTS.register("roddies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("roddies")));
	public static final Supplier<SoundEvent> SUGAREWW = SOUND_EVENTS.register("sugareww", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("sugareww")));
	public static final Supplier<SoundEvent> ROYALHURTS = SOUND_EVENTS.register("royalhurts", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("royalhurts")));
	public static final Supplier<SoundEvent> ROYALDIES = SOUND_EVENTS.register("royaldies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("royaldies")));
	public static final Supplier<SoundEvent> HEAVYAMBT = SOUND_EVENTS.register("heavyambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("heavyambt")));
	public static final Supplier<SoundEvent> HEAVYATTACK = SOUND_EVENTS.register("heavyattack", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("heavyattack")));
	public static final Supplier<SoundEvent> HEAVYROAR = SOUND_EVENTS.register("heavyroar", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("heavyroar")));
	public static final Supplier<SoundEvent> HEAVYDIES = SOUND_EVENTS.register("heavydies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("heavydies")));
	public static final Supplier<SoundEvent> STONECRASHES = SOUND_EVENTS.register("stonecrashes", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("stonecrashes")));
	public static final Supplier<SoundEvent> HEAVYHURT = SOUND_EVENTS.register("heavyhurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("heavyhurt")));
	public static final Supplier<SoundEvent> CLOGGEREXPLODES = SOUND_EVENTS.register("cloggerexplodes", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("cloggerexplodes")));
	public static final Supplier<SoundEvent> CLOGGEREXPLODING = SOUND_EVENTS.register("cloggerexploding", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("cloggerexploding")));
	public static final Supplier<SoundEvent> CLOGGERBLEED = SOUND_EVENTS.register("cloggerbleed", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("cloggerbleed")));
	public static final Supplier<SoundEvent> HUNTERDYING = SOUND_EVENTS.register("hunterdying", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("hunterdying")));
	public static final Supplier<SoundEvent> CLOOGEREATSU = SOUND_EVENTS.register("cloogereatsu", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("cloogereatsu")));
	public static final Supplier<SoundEvent> SKEEPERAMBIANCE = SOUND_EVENTS.register("skeeperambiance", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("skeeperambiance")));
	public static final Supplier<SoundEvent> SNORING = SOUND_EVENTS.register("snoring", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("snoring")));
	public static final Supplier<SoundEvent> SOMNOLENCEDIES = SOUND_EVENTS.register("somnolencedies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("somnolencedies")));
	public static final Supplier<SoundEvent> SOMNOLENCEAMBT = SOUND_EVENTS.register("somnolenceambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("somnolenceambt")));
	public static final Supplier<SoundEvent> SOMNOLENCEHURTS = SOUND_EVENTS.register("somnolencehurts", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("somnolencehurts")));
	public static final Supplier<SoundEvent> LURKERRUNNING = SOUND_EVENTS.register("lurkerrunning", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lurkerrunning")));
	public static final Supplier<SoundEvent> LURKERAMB = SOUND_EVENTS.register("lurkeramb", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lurkeramb")));
	public static final Supplier<SoundEvent> LURKERDIES = SOUND_EVENTS.register("lurkerdies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lurkerdies")));
	public static final Supplier<SoundEvent> NECRORINESAMBT = SOUND_EVENTS.register("necrorinesambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("necrorinesambt")));
	public static final Supplier<SoundEvent> DETAHCHARGE = SOUND_EVENTS.register("detahcharge", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("detahcharge")));
	public static final Supplier<SoundEvent> DEATHDYING = SOUND_EVENTS.register("deathdying", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("deathdying")));
	public static final Supplier<SoundEvent> THEDUNGEONDIES = SOUND_EVENTS.register("thedungeondies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("thedungeondies")));
	public static final Supplier<SoundEvent> THEDUNGEONAMBT = SOUND_EVENTS.register("thedungeonambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("thedungeonambt")));
	public static final Supplier<SoundEvent> THEDUNGEONHURT = SOUND_EVENTS.register("thedungeonhurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("thedungeonhurt")));
	public static final Supplier<SoundEvent> SLAM_COFFIN = SOUND_EVENTS.register("slam_coffin", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("slam_coffin")));
	public static final Supplier<SoundEvent> FLAP = SOUND_EVENTS.register("flap", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("flap")));
	public static final Supplier<SoundEvent> CLOGGER_ROARING = SOUND_EVENTS.register("clogger_roaring", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("clogger_roaring")));
	public static final Supplier<SoundEvent> CLOGGERPAIN = SOUND_EVENTS.register("cloggerpain", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("cloggerpain")));
	public static final Supplier<SoundEvent> CLOGGERAMBT = SOUND_EVENTS.register("cloggerambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("cloggerambt")));
	public static final Supplier<SoundEvent> CLOGGERDEATH = SOUND_EVENTS.register("cloggerdeath", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("cloggerdeath")));
	public static final Supplier<SoundEvent> LECHERYCRAWL = SOUND_EVENTS.register("lecherycrawl", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lecherycrawl")));
	public static final Supplier<SoundEvent> BONECRACK = SOUND_EVENTS.register("bonecrack", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("bonecrack")));
	public static final Supplier<SoundEvent> LECHERY_AMBT = SOUND_EVENTS.register("lechery_ambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lechery_ambt")));
	public static final Supplier<SoundEvent> LECHERYHURT = SOUND_EVENTS.register("lecheryhurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lecheryhurt")));
	public static final Supplier<SoundEvent> LECHERYDIES = SOUND_EVENTS.register("lecherydies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("lecherydies")));
	public static final Supplier<SoundEvent> RABIDUS_AMBT = SOUND_EVENTS.register("rabidus_ambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("rabidus_ambt")));
	public static final Supplier<SoundEvent> RABIDUS_HURT = SOUND_EVENTS.register("rabidus_hurt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("rabidus_hurt")));
	public static final Supplier<SoundEvent> RABIDUS_DIES = SOUND_EVENTS.register("rabidus_dies", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("rabidus_dies")));
	public static final Supplier<SoundEvent> CAGE_BREAK = SOUND_EVENTS.register("cage_break", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("cage_break")));
	public static final Supplier<SoundEvent> SHUTIN = SOUND_EVENTS.register("shutin", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("shutin")));
	public static final Supplier<SoundEvent> OPEN_POSSES = SOUND_EVENTS.register("open_posses", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("open_posses")));
	public static final Supplier<SoundEvent> MOONFLOWER_AMBT = SOUND_EVENTS.register("moonflower_ambt", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("moonflower_ambt")));
	public static final Supplier<SoundEvent> MOONFLOWERLIVING = SOUND_EVENTS.register("moonflowerliving", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("moonflowerliving")));
	public static final Supplier<SoundEvent> MOONFLOWERSWEEP = SOUND_EVENTS.register("moonflowersweep", () -> SoundEvent.createVariableRangeEvent(TheCorners.id("moonflowersweep")));
}

